import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {catalog} from './component-catalog.js';
const esc=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const cache=new Map();
async function loadModel(name){if(!cache.has(name))cache.set(name,fetch('/models/'+name+'.json').then(async r=>{if(!r.ok)throw Error('Model download failed');return r.json()}).catch(e=>{cache.delete(name);throw e}));return cache.get(name);}
function material(color){return new THREE.MeshStandardMaterial({color,roughness:.48,metalness:.15,side:THREE.DoubleSide})}
function cadObject(data){const group=new THREE.Group();for(const m of data.meshes){const geo=new THREE.BufferGeometry();geo.setAttribute('position',new THREE.Float32BufferAttribute(m.positions,3));geo.setIndex(m.indices);if(m.normals)geo.setAttribute('normal',new THREE.Float32BufferAttribute(m.normals,3));else geo.computeVertexNormals();const mats=[material(new THREE.Color(...(m.color||[.45,.48,.52])))];geo.addGroup(0,m.indices.length,0);if(m.faces?.length){geo.clearGroups();let offset=0;for(const face of m.faces){const start=face.first*3,count=(face.last-face.first+1)*3;if(start>offset)geo.addGroup(offset,start-offset,0);mats.push(material(new THREE.Color(...face.color)));geo.addGroup(start,count,mats.length-1);offset=start+count}if(offset<m.indices.length)geo.addGroup(offset,m.indices.length-offset,0)}group.add(new THREE.Mesh(geo,mats))}return group;}
function simplified(c){const group=new THREE.Group();const add=(w,d,h,x,y,z,color)=>{const m=new THREE.Mesh(new THREE.BoxGeometry(w,d,h),material(color));m.position.set(x,y,z);group.add(m);return m};
 const pads=c.pads.filter(p=>p.size?.every(n=>n>0));const xs=pads.flatMap(p=>[p.at[0]-p.size[0]/2,p.at[0]+p.size[0]/2]),ys=pads.flatMap(p=>[p.at[1]-p.size[1]/2,p.at[1]+p.size[1]/2]);const width=Math.max(1,Math.max(...xs)-Math.min(...xs)),depth=Math.max(1,Math.max(...ys)-Math.min(...ys));
 for(const p of pads){const m=add(p.size[0],p.size[1],.15,p.at[0],-p.at[1],0,0xc8ad6c);m.rotation.z=-((p.at[2]||c.at[2]||0)-(c.at[2]||0))*Math.PI/180;}
 if(c.ref==='P1'){add(width*.95,depth*.7,.35,0,0,2.2,0xb4bcc3);add(width*.95,depth*.7,.35,0,0,.3,0xb4bcc3);for(const x of [-1,1])add(.35,depth*.7,2,x*width*.46,0,1.2,0xb4bcc3);add(width*.7,depth*.45,.45,0,0,1.1,0x24272d)}
 else if(c.ref.startsWith('S')){add(width*.75,depth*.7,1.2,0,0,.7,0x858b91);add(width*.3,depth*.3,.9,0,0,1.7,0x24272d)}
 else if(!c.ref.startsWith('TP')){add(width*.75,depth*.75,.8,0,0,.5,0x282c33);if(c.category==='Sensors')add(width*.3,depth*.3,.08,0,0,.94,0x15171a);}
 return group;}
export function openComponentLibrary({board,initialRef,onLocate}){
 if(document.querySelector('#component-library'))return;
 const items=catalog(board),dialog=document.createElement('dialog');dialog.id='component-library';dialog.setAttribute('aria-labelledby','library-title');dialog.innerHTML=`<div class="library-header"><div><span class="eyebrow">NOWARE / COMPONENTS</span><h2 id="library-title">Know your board.</h2><p>${items.length} components · Base PCB · rotate a part to see its shape</p></div><button id="close-library" aria-label="Close component library">×</button></div><div class="library-layout"><section class="library-list-panel"><label for="library-search">Find a component</label><input id="library-search" placeholder="Name, reference or package…"><select id="library-category" aria-label="Component category"><option value="">All categories</option>${[...new Set(items.map(c=>c.category))].sort().map(c=>`<option>${c}</option>`).join('')}</select><div id="library-list"></div></section><section class="library-detail"><div id="library-description"></div><div id="component-viewer" role="img" aria-label="Interactive 3D component preview"><div id="viewer-status" role="status">Loading 3D viewer…</div></div><div class="viewer-toolbar"><span>Drag to rotate · Scroll or pinch to zoom</span><button id="model-top">Top</button><button id="model-bottom">Bottom</button><button id="model-reset">Reset view</button></div><div id="library-facts"></div></section></div>`;document.body.append(dialog);dialog.showModal();
 const $=s=>dialog.querySelector(s);let current=items.find(c=>c.ref===initialRef)||items.find(c=>c.ref==='U7')||items[0],renderer,controls,object,request=0,disposed=false,observer;
 const scene=new THREE.Scene();scene.background=new THREE.Color('#f2f4f7');const camera=new THREE.PerspectiveCamera(35,1,.01,10000);camera.up.set(0,0,1);scene.add(new THREE.HemisphereLight(0xffffff,0x68717d,2.5));for(const [x,y,z,power]of [[20,-30,40,3],[-20,10,20,2]]){const light=new THREE.DirectionalLight(0xffffff,power);light.position.set(x,y,z);scene.add(light)}
 function render(){if(!disposed&&renderer)renderer.render(scene,camera)}
 function disposeObject(){if(!object)return;scene.remove(object);object.traverse(o=>{o.geometry?.dispose();for(const m of Array.isArray(o.material)?o.material:o.material?[o.material]:[])m.dispose()});object=null;}
 function fit(view='iso'){if(!object||!controls)return;const box=new THREE.Box3().setFromObject(object),size=box.getSize(new THREE.Vector3()),center=box.getCenter(new THREE.Vector3());const distance=Math.max(size.x,size.y,size.z,1)*1.7;controls.target.copy(center);camera.position.copy(center).add(new THREE.Vector3(...(view==='top'?[0,0,distance]:view==='bottom'?[0,0,-distance]:[distance*.8,-distance,distance*.8])));camera.near=distance/1000;camera.far=distance*100;camera.updateProjectionMatrix();controls.minDistance=distance*.15;controls.maxDistance=distance*8;controls.update();render()}
 try{renderer=new THREE.WebGLRenderer({antialias:true,alpha:false});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.outputColorSpace=THREE.SRGBColorSpace;$('#component-viewer').append(renderer.domElement);controls=new OrbitControls(camera,renderer.domElement);controls.addEventListener('change',render);observer=new ResizeObserver(()=>{const el=$('#component-viewer');renderer.setSize(el.clientWidth,el.clientHeight);camera.aspect=el.clientWidth/el.clientHeight;camera.updateProjectionMatrix();render()});observer.observe($('#component-viewer'));}catch{$('#viewer-status').textContent='3D rendering is unavailable in this browser. Component details and source links are still available.';}
 function list(){const query=$('#library-search').value.toLowerCase(),category=$('#library-category').value;const found=items.filter(c=>(!category||c.category===category)&&`${c.ref} ${c.value} ${c.footprint}`.toLowerCase().includes(query));$('#library-list').innerHTML=found.map(c=>`<button data-library-ref="${c.ref}" aria-pressed="${c.ref===current.ref}"><span class="library-part-symbol">${c.category==='Capacitors'?'⊣':c.category==='Resistors'?'▱':c.category==='LEDs'?'☼':'▦'}</span><span><strong>${c.ref} <b>${esc(c.value)}</b></strong><small>${c.category} · ${c.quality}</small></span></button>`).join('')||'<p class="empty">No matching components.</p>';for(const b of dialog.querySelectorAll('[data-library-ref]'))b.onclick=()=>choose(items.find(c=>c.ref===b.dataset.libraryRef));}
 async function choose(c){current=c;const id=++request;list();$('#library-description').innerHTML=`<div class="library-part-heading"><div><span class="eyebrow">${c.category}</span><h3>${c.ref} <span>${esc(c.value)}</span></h3></div><span class="library-quality ${c.model?'':'approximate'}">${c.quality}</span></div><p>${esc(c.role)}</p>`;$('#library-facts').innerHTML=`<p class="model-note">${esc(c.note)}</p><dl><div><dt>Footprint</dt><dd>${esc(c.footprint)}</dd></div><div><dt>Placement</dt><dd>${c.layer==='F.Cu'?'Front':'Back'} · ${c.at[0].toFixed(2)}, ${c.at[1].toFixed(2)} mm</dd></div><div><dt>Footprint pads</dt><dd>${c.pads.length} (includes any duplicated / thermal pads)</dd></div><div><dt>Model bounds</dt><dd id="model-bounds">${c.model?'Loading…':'Approximate geometry'}</dd></div></dl><div class="library-links"><button id="locate-library-part">Locate ${c.ref} on board ↗</button><a href="${c.ref==='U7'?'https://github.com/espressif/kicad-libraries/blob/dd76561812ab300351234ba6e0ec1295641796f0/3dmodels/espressif.3dshapes/ESP32-H2-MINI-1.STEP':`https://github.com/hyperchi/AirCube/blob/${board.commit}/kicad/AirCube.step`}" target="_blank" rel="noreferrer">${c.model?'CAD source':'Source assembly'} ↗</a><a href="/models/README.md" target="_blank" rel="noreferrer">Model provenance</a></div>`;$('#locate-library-part').onclick=()=>{dialog.close();onLocate(c.ref)};
 if(!renderer)return;disposeObject();render();$('#viewer-status').hidden=false;$('#viewer-status').textContent='Loading model…';try{const data=c.model?await loadModel(c.model):null;if(id!==request||disposed)return;object=data?cadObject(data):simplified(c);scene.add(object);$('#model-bounds').textContent=data?data.dimensions.map(v=>v.toFixed(2)).join(' × ')+' mm (CAD envelope)':'Approximate geometry';$('#viewer-status').hidden=true;renderer.domElement.dataset.model=c.model||'simplified';renderer.domElement.dataset.component=c.ref;fit();}catch{if(id!==request||disposed)return;$('#viewer-status').textContent='Could not load this 3D model. Select the part again to retry.';}}
 function cleanup(){disposed=true;request++;observer?.disconnect();controls?.dispose();disposeObject();renderer?.dispose();dialog.remove()}
 dialog.addEventListener('close',cleanup,{once:true});$('#close-library').onclick=()=>dialog.close();dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close()}});$('#library-search').oninput=list;$('#library-category').onchange=list;$('#model-top').onclick=()=>fit('top');$('#model-bottom').onclick=()=>fit('bottom');$('#model-reset').onclick=()=>fit();choose(current);
}
