const upgradedModels={
 U2:{model:'ens161',quality:'Datasheet reconstruction',sourceLabel:'Package drawing',source:'https://www.sciosense.com/wp-content/uploads/2024/12/ENS161-Datasheet.pdf#page=41',note:'Reconstructed from ScioSense’s 3 × 3 × 0.83 mm package drawing: 0.3 mm gas inlet and nine underside contacts. Lid seam and finishes are illustrative; this is not manufacturer CAD.'},
 U10:{model:'ens210',quality:'Datasheet reconstruction',sourceLabel:'Package drawing',source:'https://www.sciosense.com/wp-content/uploads/2023/12/ENS210-Datasheet.pdf#page=37',note:'Reconstructed from the 2 × 2 × 0.75 mm QFN drawing, with recessed sensing cavity, four terminals and exposed pad. Surface finish and cavity interior are illustrative; this is not manufacturer CAD.'},
 U6:{model:'sot23-5',quality:'Package CAD',source:'https://github.com/KiCad/kicad-packages3D/blob/b8b3cfdfad88ba66f21002b3de51dc6f7d55ba5a/Package_TO_SOT_SMD.3dshapes/SOT-23-5.step',note:'KiCad SOT-23-5 package with five formed leads, matching the board’s SOT25-style footprint. Generic package CAD; vendor height, markings and tolerances may differ.'},
 P1:{model:'usb4105',quality:'Community CAD',source:'https://gitlab.com/kicad/libraries/kicad-packages3D/-/blob/43578c8e7219955321f06043dec41f6355848969/Connector_USB.3dshapes/USB_C_Receptacle_GCT_USB4105-xx-A_16P_TopMnt_Horizontal.step',note:'KiCad USB4105 CAD with metal shell, mating tongue, contacts and mounting stakes. The source board uses this receptacle footprint despite its generic USB_C_Plug value. Check the ordered stake-length variant.'},
 S3:{model:'tl1016',quality:'Manufacturer CAD',source:'https://configured-product-images.s3.amazonaws.com/stp3dmodels/TL1016AAFxxxQG.stp',note:'Official E-Switch TL1016AAF family STEP model, with side actuator, metal cover and terminals. Family model covers multiple operating-force variants; finishes may differ.'},
 S2:{model:'rkb2',quality:'Datasheet reconstruction',sourceLabel:'Package drawing',source:'https://www.littelfuse.com/assetdocs/littelfuse-c-k-tactile-rk-series-datasheet?assetguid=ba27fd10-c379-497f-a7d8-b8be543ce75e',note:'The BOM specifies C&K RKB2SJK250SMTR LFS. Reconstructed 4.2 × 3.2 mm body, 2.5 mm height and J-bend terminals from the RK drawing. Actuator details and finishes are illustrative. The original footprint has a different PTS830 tag; confirm fit before fabrication.'},
 TP2:{model:'testpoint-pad',quality:'Board copper',sourceLabel:'PCB source',source:'https://github.com/hyperchi/AirCube/blob/bd857275c1f02efbec6942a96e433bde9d4d417e/kicad/AirCube.kicad_pcb',note:'Actual 1.5 × 1.5 mm test-pad opening and silkscreen outline. The surrounding board coupon and copper thickness are illustrative. This is exposed PCB copper, not a purchased component.'}
};
export function describePart(c){
 const ref=c.ref;
 if(ref.startsWith('R'))return {category:'Resistors',role:'Limits current, sets logic levels or forms a signal network. Its exact job depends on the connected nets.',model:'resistor-0603',quality:'Package CAD',note:'KiCad 0603 package CAD; value and markings are not modeled.'};
 if(ref.startsWith('C'))return {category:'Capacitors',role:'Stores a small amount of charge to stabilize supply rails and filter noise.',model:'capacitor-0603',quality:'Package CAD',note:'KiCad 0603 package CAD; actual height varies with vendor, value and voltage rating.'};
 if(ref.startsWith('LED'))return {category:'LEDs',role:'Addressable RGB LED used to display the air-quality indication.',model:'rgb-led',quality:'Source CAD',note:'IN-PI15 package geometry from the original board STEP assembly, with illustrative body/contact materials restored. Internal LED dies and encapsulant optics are not modeled.'};
 const meta={U7:['Controller','Runs the sensor and LED firmware. ESP32-H2 includes Bluetooth LE and IEEE 802.15.4 (Thread/Zigbee), not Wi-Fi.','esp32-h2-mini-1','Manufacturer CAD'],U2:['Sensors','ENS161 gas sensor for volatile organic compounds and estimated air-quality outputs.'],U10:['Sensors','ENS210 measures temperature and humidity on the Base board.'],U5:['Power','AP2120 regulator supplies the 1.8 V rail from 3.3 V.','sot23','Package CAD'],U6:['Power','AP2205 regulator supplies the 3.3 V rail from the USB power path.'],Q1:['Transistors','BSS138 MOSFET used in the LED data level-shifting circuit.','sot23','Package CAD'],D5:['Protection','TPD1E10B06 protects against electrostatic discharge.','sod523','Package CAD'],P1:['Connectors','USB connector brings power and USB signals onto the board.'],S2:['Switches','Top-actuated tactile button. The BOM specifies C&K RKB2SJK250SMTR LFS.'],S3:['Switches','Right-angle pushbutton connected to the boot-control circuit.'],TP2:['Test points','Exposed copper pad for probing or test access.']};
 const [category,role,model,quality]=meta[ref]||['Other','Component from the original KiCad board.'];
 return {category,role,model,quality:quality||'Simplified preview',...upgradedModels[ref],note:upgradedModels[ref]?.note||(model?(ref==='U7'?'Official Espressif STEP geometry. CAD appearance may differ from production markings.':'KiCad package geometry with body and lead materials. Exact vendor markings and tolerances are not modeled.'):'No matching CAD model was available in the source assembly. This preview uses footprint pad locations and an approximate body; it is not a dimensional reference.')};
}
const packageSources={'resistor-0603':'Resistor_SMD.3dshapes/R_0603_1608Metric.step','capacitor-0603':'Capacitor_SMD.3dshapes/C_0603_1608Metric.step',sot23:'Package_TO_SOT_SMD.3dshapes/SOT-23.step',sod523:'Diode_SMD.3dshapes/D_SOD-523.step'};
export function catalog(board){return board.components.filter(c=>!c.ref.includes('*')).map(c=>{const meta=describePart(c);return {...c,...meta,...(packageSources[meta.model]?{source:'https://github.com/KiCad/kicad-packages3D/blob/b8b3cfdfad88ba66f21002b3de51dc6f7d55ba5a/'+packageSources[meta.model]}:{})}}).sort((a,b)=>a.ref.localeCompare(b.ref,undefined,{numeric:true}));}

export const connectionOptions=[
 {ref:'WIFI-C3',value:'Wi-Fi · ESP32-C3-MINI-1',category:'Connection options',candidate:true,kind:'wifi',model:'esp32-c3-mini-1',quality:'Manufacturer CAD',footprint:'New module footprint required',role:'Replace the H2 controller with an ESP32-C3 module for 2.4 GHz Wi-Fi and Bluetooth LE. Connect to an existing Wi-Fi access point.',note:'Official Espressif CAD. Proposed replacement, not fitted to this PCB. This requires a new footprint, antenna clearance, pin mapping and firmware port.',source:'https://github.com/espressif/kicad-libraries/blob/dd76561812ab300351234ba6e0ec1295641796f0/3dmodels/espressif.3dshapes/ESP32-C3-MINI-1.STEP',requires:['USB-C input and a suitable 3.3 V supply','Wi-Fi access point and network provisioning','Sensor / LED pin remapping and firmware port'],interface:'Controller replacement; remap GPIO, I²C and LED data'},
 {ref:'SIM-BG95',value:'Cellular + SIM · Quectel BG95',category:'Connection options',candidate:true,kind:'cellular',model:'bg95',quality:'Community CAD',footprint:'New modem footprint and SIM interface required',dimensions:[23.6,19.9,2.2],role:'Keep the ESP32-H2 and add an LTE-M modem for sensor reports through a mobile carrier. The SIM identifies the subscription; the modem provides the radio.',note:'Detailed BG95 STEP geometry with shield and underside contacts, from the community kicad-open-3d collection. This shows the modem module only; the SIM holder, antenna and power circuitry are separate parts. Confirm the exact regional variant and land pattern before PCB design.',source:'https://github.com/brunoeagle/kicad-open-3d/blob/426b1d1223f621a05e9c411ded52347c1f5b2d03/BG95.step',requires:['USB-C input with sufficient current and a dedicated modem rail','SIM holder or compatible eSIM, active plan and correct APN','Band-matched cellular antenna and ESD protection','UART control, enable/reset and level shifting as required'],interface:'UART + modem control; validate the selected variant’s logic levels'}
];
export function libraryCatalog(board){return [...catalog(board),...connectionOptions];}
