export function describePart(c){
 const ref=c.ref;
 if(ref.startsWith('R'))return {category:'Resistors',role:'Limits current, sets logic levels or forms a signal network. Its exact job depends on the connected nets.',model:'resistor-0603',quality:'Package CAD',note:'Generic 0603 package from the source STEP assembly; value and markings are not modeled.'};
 if(ref.startsWith('C'))return {category:'Capacitors',role:'Stores a small amount of charge to stabilize supply rails and filter noise.',model:'capacitor-0603',quality:'Package CAD',note:'Generic 0603 package from the source STEP assembly; actual height varies with vendor, value and voltage rating.'};
 if(ref.startsWith('LED'))return {category:'LEDs',role:'Addressable RGB LED used to display the air-quality indication.',model:'rgb-led',quality:'Source CAD',note:'IN-PI15 package geometry from the original board STEP assembly.'};
 const meta={U7:['Controller','Runs the sensor and LED firmware. ESP32-H2 includes Bluetooth LE and IEEE 802.15.4 (Thread/Zigbee), not Wi-Fi.','esp32-h2-mini-1','Manufacturer CAD'],U2:['Sensors','ENS161 gas sensor for volatile organic compounds and estimated air-quality outputs.'],U10:['Sensors','ENS210 measures temperature and humidity on the Base board.'],U5:['Power','AP2120 regulator supplies the 1.8 V rail from 3.3 V.','sot23','Package CAD'],U6:['Power','AP2205 regulator supplies the 3.3 V rail from the USB power path.'],Q1:['Transistors','BSS138 MOSFET used in the LED data level-shifting circuit.','sot23','Package CAD'],D5:['Protection','TPD1E10B06 protects against electrostatic discharge.','sod523','Package CAD'],P1:['Connectors','USB connector brings power and USB signals onto the board.'],S2:['Switches','Physical switch footprint in the source board. Inspect its pins and nets to determine its wiring.'],S3:['Switches','Right-angle pushbutton connected to the boot-control circuit.'],TP2:['Test points','Exposed copper pad for probing or test access.']};
 const [category,role,model,quality]=meta[ref]||['Other','Component from the original KiCad board.'];
 return {category,role,model,quality:quality||'Simplified preview',note:model?(ref==='U7'?'Official Espressif STEP geometry. CAD appearance may differ from production markings.':'Generic package geometry from the source board STEP assembly.'):'No matching CAD model was available in the source assembly. This preview uses footprint pad locations and an approximate body; it is not a dimensional reference.'};
}
export function catalog(board){return board.components.filter(c=>!c.ref.includes('*')).map(c=>({...c,...describePart(c)})).sort((a,b)=>a.ref.localeCompare(b.ref,undefined,{numeric:true}));}
