import {profiles,defaults,normalize,evaluate,sequence} from './design-simulation.js';
const esc=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=(v,d=1)=>Number(v).toLocaleString(undefined,{maximumFractionDigits:d});
export function mountDesignLab({board,selectPart,onConnectionChange}){
 const aside=document.querySelector('.simulation');
 const environment=document.createElement('div');environment.id='environment-panel';environment.setAttribute('role','tabpanel');environment.setAttribute('aria-labelledby','environment-tab');
 while(aside.firstChild)environment.append(aside.firstChild);
 aside.append(environment);aside.insertAdjacentHTML('afterbegin','<div class="lab-tabs" role="tablist" aria-label="Simulator"><button id="design-tab" role="tab" aria-selected="true" aria-controls="design-panel">Design lab</button><button id="environment-tab" role="tab" aria-selected="false" aria-controls="environment-panel" tabindex="-1">Air & LEDs</button></div>');
 const root=document.createElement('div');root.id='design-panel';root.setAttribute('role','tabpanel');root.setAttribute('aria-labelledby','design-tab');aside.append(root);environment.hidden=true;
 for(const tab of aside.querySelectorAll('[role=tab]')){tab.onclick=()=>{const design=tab.id==='design-tab';root.hidden=!design;environment.hidden=design;onConnectionChange(design?state.kind:null);for(const t of aside.querySelectorAll('[role=tab]')){t.setAttribute('aria-selected',String(t===tab));t.tabIndex=t===tab?0:-1;}};tab.onkeydown=e=>{if(e.key==='ArrowLeft'||e.key==='ArrowRight'){const other=aside.querySelector(`[role=tab]:not(#${tab.id})`);other.click();other.focus();}};}
 let state=normalize(defaults),baseline=null,timer=null;try{const saved=JSON.parse(localStorage.getItem('noware-design-lab'));if(saved){state=normalize(saved.state);baseline=saved.baseline?normalize(saved.baseline):null}}catch{}
 const save=()=>{try{localStorage.setItem('noware-design-lab',JSON.stringify({state,baseline}))}catch{}};
 const stop=()=>{clearTimeout(timer);timer=null;const b=root.querySelector('#run-design');if(b)b.disabled=false;};
 function field(key,label,unit,min,max,step=1){return `<label class="lab-field" for="design-${key}"><span>${label} <small>${unit}</small></span><input id="design-${key}" data-setting="${key}" type="number" min="${min}" max="${max}" step="${step}" value="${state[key]}"></label>`;}
 function render(){stop();const p=profiles[state.kind];root.innerHTML=`<div class="panel-heading">Try a different design <span class="badge">WHAT IF</span></div><p class="sim-intro">Powered by USB-C. Change the connection and check the power budget.</p><label class="lab-field">Starting hardware<select id="design-variant"><option value="base">Base · ENS161 + ENS210</option><option value="pro">Pro · ENS161 + SCD41 + VCNL4040</option></select></label><label class="lab-field">Connection<select id="design-kind">${Object.entries(profiles).map(([key,p])=>`<option value="${key}" ${state.kind===key?'selected':''}>${p.name}</option>`).join('')}</select></label><p class="lab-context">Both the Base PCB and supplied Pro schematic use ESP32-H2: Bluetooth + Thread/Zigbee, no Wi-Fi. A SIM needs a cellular modem; it is not a replacement radio by itself.</p>
 <div class="lab-route" aria-label="Proposed data path"><span>${state.variant==='pro'?'VOC + CO₂ + light':'VOC + temp/RH'}</span><b>→</b><button id="design-controller">${state.kind==='wifi'?'New Wi-Fi MCU':'U7 · ESP32-H2'}</button><b>→</b><span>${state.kind==='cellular'?'Modem + SIM':state.kind==='wifi'?'Wi-Fi router':'Thread gateway'}</span><b>→</b><span>Cloud</span></div>
 <div class="lab-fields">${field('interval','Send every','seconds',1,86400)}${field('payload','Reading size','bytes',1,1000000)}${field('usbCurrent','USB-C input limit','mA at 5 V',1,5000)}${field('baseMw','Rest of board','mW',0,10000)}${field('railV','Radio supply','V',1,6,.1)}${field('supply','Rail capacity','mA',1,10000)}</div>
 <label class="lab-field">Signal<select id="design-signal"><option value="good">Good · no retries</option><option value="weak">Weak · one retry</option><option value="none">No coverage</option></select></label>
 <div class="lab-checks">${[['network',state.kind==='cellular'?'Carrier available':state.kind==='wifi'?'Wi-Fi available':'Gateway available'],['antenna','Antenna connected'],...(state.kind==='cellular'?[['sim','SIM provisioned']]:[])].map(([key,label])=>`<label><input type="checkbox" data-flag="${key}" ${state[key]?'checked':''}>${label}</label>`).join('')}</div>
 <div id="design-results" aria-live="polite"></div><button id="run-design" class="lab-primary">▶ Run one reading</button><ol id="design-events" class="lab-events" aria-live="polite"><li>Run to follow a reading from the sensor to the cloud.</li></ol>
 <details class="lab-details"><summary>Compare all connection options</summary><div id="design-compare"></div><p>Same 5 V USB-C input budget, workload and conditions. Each option uses its planned radio voltage; verify a dedicated rail before choosing it.</p></details>
 <details class="lab-details" open><summary>What changes on the PCB?</summary><ul>${p.changes.map(c=>`<li>${esc(c)}</li>`).join('')}</ul><button class="lab-link" id="inspect-original">Inspect original U7</button><div class="lab-candidates">${state.kind==='cellular'?candidatePins():''}</div><p>${state.variant==='pro'?'Pro sensors come from your schematic photos; their placement is not in this Base PCB file. Update “Rest of board” power for the Pro sensor load.':'The displayed PCB remains the original Base design.'} New modules need layout, routing and electrical review.</p></details>
 <details class="lab-details"><summary>Model assumptions · edit values</summary><p>Illustrative starting values, not datasheet measurements. Planning rail windows are 3.0–3.6 V for the MCU options and 3.3–4.3 V for the generic cellular option; check the exact modem variant before powering it. Reconnect on every report; a weak signal doubles connection and transfer time and adds one retry. No carrier timing, TLS handshake or RF simulation.</p><div class="lab-fields">${[['peak','Peak radio current','mA',1,10000],['active','Active radio current','mA',.01,5000],['idle','Sleep radio current','mA',0,1000],['attach','Connect time','s',.01,600],['rate','Effective throughput','kb/s',.01,100000],['overhead','Protocol overhead','bytes',0,100000]].map(([key,label,unit,min,max])=>`<label class="lab-field"><span>${label} <small>${unit}</small></span><input data-assumption="${key}" type="number" min="${min}" max="${max}" step="any" value="${state.overrides[state.kind][key]}"></label>`).join('')}${field('efficiency','Power conversion','% efficiency',1,100)}</div><p>“Rest of board” covers sensors, LEDs, controller and regulator losses outside the modeled radio. Measure it for your firmware. USB-C input is modeled at 5 V. Set its current limit from the source/cable rating and advertised or negotiated capability. No USB Power Delivery negotiation is simulated.</p><a href="${p.source}" target="_blank" rel="noreferrer">Manufacturer: connectivity and module reference ↗</a></details>
 <div class="lab-actions"><button id="save-baseline">Save baseline</button><button id="export-design">Export design</button><button id="reset-design">Reset</button></div><p class="lab-limit">Planning simulator · estimates, not circuit or firmware execution. Changes are saved in this browser.</p>`;
 root.querySelector('#design-variant').value=state.variant;root.querySelector('#design-variant').onchange=e=>{state.variant=e.target.value;save();render()};
 root.querySelector('#design-kind').onchange=e=>{state.kind=e.target.value;state.railV=profiles[state.kind].voltage;save();render();onConnectionChange(state.kind)};root.querySelector('#design-signal').value=state.signal;root.querySelector('#design-signal').onchange=e=>{state.signal=e.target.value;changed()};
 for(const el of root.querySelectorAll('[data-setting]'))el.onchange=()=>{state[el.dataset.setting]=el.value;state=normalize(state);el.value=state[el.dataset.setting];changed()};
 for(const el of root.querySelectorAll('[data-assumption]'))el.onchange=()=>{state.overrides[state.kind][el.dataset.assumption]=el.value;state=normalize(state);el.value=state.overrides[state.kind][el.dataset.assumption];changed()};
 for(const el of root.querySelectorAll('[data-flag]'))el.onchange=()=>{state[el.dataset.flag]=el.checked;changed()};
 root.querySelector('#design-controller').onclick=root.querySelector('#inspect-original').onclick=()=>selectPart('U7');
 root.querySelector('#run-design').onclick=run;
 root.querySelector('#save-baseline').onclick=()=>{baseline=normalize(state);save();results()};
 root.querySelector('#reset-design').onclick=()=>{state=normalize(defaults);baseline=null;save();render();onConnectionChange(state.kind)};
 root.querySelector('#export-design').onclick=()=>{const data={schema:1,type:'noware-design-study',sourceCommit:board.commit,inputs:state,result:evaluate(state),baseline:baseline?{inputs:baseline,result:evaluate(baseline)}:null,sequence:sequence(state),limits:'Illustrative planning model; no PCB modification, circuit solver, firmware execution or real network connection.',sources:Object.values(profiles).map(p=>p.source)};const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='noware-design-study.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};results();}
 function candidatePins(){const u=board.components.find(c=>c.ref==='U7');const pins=u.pads.map(p=>({pad:p.number,name:board.nets[p.net]})).filter(p=>/^unconnected-\(U7-(IO\d+|RXD0|TXD0)-/.test(p.name));return `<strong>Unrouted signal pads in source board</strong><p>${pins.map(p=>`${esc(p.name.match(/U7-(.*)-Pad/)[1])} (pad ${esc(p.pad)})`).join(', ')}</p><p>Candidate signals only: check boot straps, debug use and firmware mapping before assigning UART. NC pads are reserved, not spare GPIOs.</p>`;}
 function changed(){stop();root.querySelector('#design-events').innerHTML='<li>Settings changed. Run again to trace this design.</li>';save();results();}
 function results(){const r=evaluate(state),b=baseline?evaluate(baseline):null;root.querySelector('#design-results').innerHTML=`<div class="lab-status ${r.connected?'':'fault'}"><strong>${r.connected?(r.backlog>0?'Reports arrive faster than they can send':'Connection possible under these assumptions'):'Design cannot deliver readings'}</strong>${r.problems.map(p=>`<span>${esc(p)}</span>`).join('')}</div><div class="lab-metrics"><div><span>USB-C input power</span><strong>${fmt(r.inputMw/1000,2)} <small>W</small></strong></div><div><span>Daily energy</span><strong>${fmt(r.energyWhPerDay,2)} <small>Wh</small></strong></div><div><span>Estimated data / 30 days</span><strong>${fmt(r.dataMB,2)} <small>MB</small></strong></div><div><span>Connection + send</span><strong>${fmt(r.cycle,2)} <small>s</small></strong></div></div><p class="lab-budget">USB-C · 5 V · ${fmt(r.usbAverageMa)} mA average · ${fmt(r.usbPeakMa)} mA modeled peak · ${fmt(r.usbHeadroomMa)} mA input headroom<br>${fmt(r.delivered,0)} / ${fmt(r.requested,0)} readings per day delivered · ${fmt(r.utilization*100)}% radio duty · ${fmt(r.required,0)} mA modeled peak incl. board load</p>${b?`<p class="lab-baseline">Baseline: ${esc(b.p.name)} · USB input ${fmt((r.inputMw-b.inputMw)/1000,2)} W change · daily energy ${fmt(r.energyWhPerDay-b.energyWhPerDay,2)} Wh change <button id="clear-baseline">Clear</button></p>`:''}`;root.querySelector('#clear-baseline')?.addEventListener('click',()=>{baseline=null;save();results()});
 root.querySelector('#design-compare').innerHTML=`<table><thead><tr><th>Option</th><th>USB W</th><th>Wh/day</th><th>Delivery</th></tr></thead><tbody>${Object.keys(profiles).map(kind=>{const x=evaluate({...state,kind,railV:profiles[kind].voltage},kind);return `<tr class="${kind===state.kind?'chosen':''}"><th>${kind==='cellular'?'LTE-M + SIM':kind==='wifi'?'Wi-Fi':'Thread'}</th><td>${fmt(x.inputMw/1000,2)}</td><td>${fmt(x.energyWhPerDay,2)}</td><td>${x.connected?(x.backlog>0?'Backlog':'Possible'):'Blocked'}</td></tr>`}).join('')}</tbody></table>`;}
 function run(){stop();const events=sequence(state);root.querySelector('#run-design').disabled=true;const list=root.querySelector('#design-events');list.innerHTML='';let i=0,time=0;const next=()=>{const event=events[i++];time+=event.duration;const li=document.createElement('li');li.className=event.failed?'failed':'complete';li.innerHTML=`<span class="event-time">+${fmt(time,2)}s</span><strong>${esc(event.label)}</strong><small>${esc(event.detail)}</small>`;list.append(li);if(i<events.length)timer=setTimeout(next,600);else{const note=document.createElement('li');note.textContent='Preview complete. Playback is accelerated; times are modeled.';list.append(note);stop();}};next();}
 render();onConnectionChange(state.kind);
 return {setConnection(kind){if(!profiles[kind])return;state.kind=kind;state.railV=profiles[kind].voltage;save();render();aside.querySelector('#design-tab').click();root.scrollIntoView({behavior:'smooth',block:'nearest'});}};
}
